### ISSUE TITLE
Adding AnyChart licence key

### ISSUE THREAD

**Issue by ImranAhmed** [anychart-integrations/anychart-angular4#3]
Hi,

Is there an example for best practice in adding the AnyChart licence key to an angular 4/5 project?

**Comment by loki20beta** [comment]
Yes, you can specify the license key in an Angular 4/5 app.

Basically, you can specify it in ngOnInit() function like this:
```
ngOnInit() {
anychart.licenseKey('YOUR-LICENSE-KEY');
//creating chart code
}
```

**Comment by ImranAhmed** [comment]
Thanks. 

Do you need to do this in every component that uses AnyChart? Can you not specify it in AppModule or somewhere global?

**Comment by loki20beta** [comment]
Hmm. Let me think about it and get back to you. It makes sense to do it on another level, I'll ask developers to assist.

**Comment by Shestac92** [comment]
@ImranAhmed 
You can specify your license key globally in the Angular application.
You should add _anychart.licenseKey('YOUR-LICENSE-KEY');_ in _main.ts_ file after AnyChart js imports.
Like this:
```
//main.ts
import 'anychart/dist/js/anychart-base.min.js';
import 'anychart/dist/js/anychart-ui.min.js';
anychart.licenseKey('YOUR-LICENSE-KEY');
```
